import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';
import { Noto_Sans_KR } from 'next/font/google';
import './globals.css';
import { SessionProvider } from 'next-auth/react';
import { Header } from '@/components/organisms';
import { layoutContainer } from './layout.css';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

const notoSans = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'NextGacha',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      {/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */}
      {/* <body className={`${notoSans.className} ${layoutContainer}`}> */}
      <body className={`${notoSans.className} ${layoutContainer}`}>
        <SessionProvider>
          <div>
            <Header />
            {children}
          </div>
        </SessionProvider>
      </body>
      {/* </body> */}
    </html>
  );
}
